// Prepares the Papela design-system package for the Claude Design converter
// (cfg.buildCmd). papela-site is a Next.js app, not a published library, so we
// synthesize the "dist" the converter expects:
//   1. .design-sync/pkg/index.ts      — re-exports the synced components
//   2. .design-sync/pkg/types/        — real .d.ts via tsc (the props contract)
//   3. .design-sync/pkg/papela.css    — app/globals.css compiled by Tailwind v4,
//      scanning the app + previews + a safelist so the design agent's own
//      layout classes resolve too.
// Run from the repo root: node .design-sync/build-ds.mjs
import { execFileSync } from "node:child_process";
import { cpSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import postcss from "postcss";
import tailwind from "@tailwindcss/postcss";

const ROOT = process.cwd();
const PKG = join(ROOT, ".design-sync/pkg");
const components = JSON.parse(readFileSync(join(PKG, "components.json"), "utf8"));

// -- 0. asset-rewritten copy of components/site ------------------------------
// Components reference public/ files by root path ("/site/logo-ring.svg",
// "/images/..."). Those don't exist next to the bundle in Claude Design, so the
// RUNTIME entry bundles a copy of components/site with root asset paths pointed
// at the live site (www.papela-atelier.com serves them with CORS *). Types and
// JSDoc still come from the originals. Relative imports stay inside the dir;
// @/ imports resolve to the repo, so the stores stay single-instance.
export const ASSET_ORIGIN = "https://www.papela-atelier.com";
const ASSET_RX = /(["'`(])\/(site|images|icons|videos|logos?)\//g;
const COPY = join(PKG, "src/components/site");
rmSync(join(PKG, "src"), { recursive: true, force: true });
cpSync(join(ROOT, "components/site"), COPY, { recursive: true });
let rewrites = 0;
(function walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) { walk(p); continue; }
    if (!/\.(tsx?|jsx?)$/.test(e.name)) continue;
    const src = readFileSync(p, "utf8");
    const out = src.replace(ASSET_RX, (_, q, d) => { rewrites++; return `${q}${ASSET_ORIGIN}/${d}/`; });
    if (out !== src) writeFileSync(p, out);
  }
})(COPY);

// -- 1. entry --------------------------------------------------------------
// Non-component exports the previews (and the design agent) need: the Zustand
// stores behind the cart and product drawer, so a design can open/fill them.
export const ICONS = ["ArrowRightIcon", "ArrowLeftIcon", "PlusIcon", "MinusIcon", "XMarkIcon", "CheckIcon", "CheckCircleIcon", "ChevronRightIcon", "ChevronLeftIcon", "ChevronDownIcon", "SparklesIcon", "StarIcon", "HeartIcon", "ShoppingBagIcon", "MapPinIcon", "ClockIcon", "CalendarDaysIcon", "ScissorsIcon", "SwatchIcon", "AcademicCapIcon", "CakeIcon", "UserGroupIcon", "BuildingStorefrontIcon", "PhoneIcon", "EnvelopeIcon"];
const STORES = [
  'export { useCartStore, cartKey, COSTO_ENVIO } from "../../lib/stores/cartStore";',
  'export type { CartItem, TipoEnvio } from "../../lib/stores/cartStore";',
  'export { useProductDrawerStore } from "../../lib/stores/productDrawerStore";',
  // Heroicons (24/solid) the site uses most, so designs can use the same icons.
  // Excluded from the component list via componentSrcMap: null in config.json.
  `export { ${ICONS.join(", ")} } from "@heroicons/react/24/solid";`,
];
const lines = [
  ...Object.entries(components).map(
    ([name, file]) => `export { default as ${name} } from "./src/components/site/${file}";`,
  ),
  ...STORES,
];
writeFileSync(join(PKG, "index.ts"), `// generated by .design-sync/build-ds.mjs — do not edit\n${lines.join("\n")}\n`);

// -- 2. declarations -------------------------------------------------------
rmSync(join(PKG, "types"), { recursive: true, force: true });
const dtsConfig = join(PKG, "tsconfig.dts.json");
writeFileSync(
  dtsConfig,
  JSON.stringify(
    {
      extends: "../../tsconfig.json",
      compilerOptions: {
        noEmit: false,
        declaration: true,
        emitDeclarationOnly: true,
        noEmitOnError: false,
        incremental: false,
        outDir: "types",
        rootDir: "../..",
        plugins: [],
      },
      include: [],
      files: [
        "../../next-env.d.ts",
        "../../lib/stores/cartStore.ts",
        "../../lib/stores/productDrawerStore.ts",
        ...Object.values(components).map((f) => `../../components/site/${f}.tsx`),
      ],
    },
    null,
    2,
  ),
);
try {
  execFileSync(join(ROOT, "node_modules/.bin/tsc"), ["-p", dtsConfig], { stdio: "pipe" });
} catch (e) {
  // Type errors don't block emit (noEmitOnError:false); surface them anyway.
  const out = String(e.stdout || "") + String(e.stderr || "");
  if (out.trim()) console.error(`  tsc reported:\n${out.trim().split("\n").slice(0, 20).join("\n")}`);
}
rmSync(dtsConfig, { force: true });
writeFileSync(
  join(PKG, "types/index.d.ts"),
  [
    ...Object.entries(components).map(([name, file]) => `export { default as ${name} } from "./components/site/${file}";`),
    ...STORES.map((l) => l.replace("../../", "./")),
  ].join("\n") + "\n",
);

// -- 3. CSS ----------------------------------------------------------------
// Safelist: the vocabulary the conventions header teaches the design agent.
// Tailwind v4 `@source inline()` with brace expansion.
const colors = "verde,verde-light,cremita,cremita-2,cremita-3,terracota,durazno,text,muted,border,bg,white,black,transparent";
const sp = "0,0.5,1,1.5,2,2.5,3,4,5,6,8,10,12,14,16,20,24,28,32";
const safelist = [
  `{hover:,}{bg,text,border}-{${colors}}`,
  `{,md:,lg:}{p,px,py,pt,pb,pl,pr,m,mx,my,mt,mb,gap,gap-x,gap-y,space-y,space-x}-{${sp}}`,
  `{,md:,lg:}{flex,grid,block,inline-flex,inline-block,hidden,contents}`,
  `{,md:,lg:}{flex-col,flex-row,flex-wrap,flex-1,shrink-0,grow,items-center,items-start,items-end,items-stretch,justify-center,justify-between,justify-start,justify-end,self-center}`,
  `{,md:,lg:}grid-cols-{1,2,3,4,5,6,12}`,
  `{,md:,lg:}col-span-{1,2,3,4,6,12,full}`,
  `{,md:,lg:}text-{xs,sm,base,lg,xl,2xl,3xl,4xl,5xl,6xl,left,center,right}`,
  `{,md:}{w,h}-{full,auto,screen,fit,10,12,16,20,24,32,40,48,64}`,
  `{,md:}max-w-{xs,sm,md,lg,xl,2xl,3xl,4xl,5xl,prose}`,
  `w-[90%]`, `mx-auto`, `min-h-screen`,
  `rounded{,-md,-lg,-xl,-2xl,-3xl,-full}`,
  `font-{serif,sans,extralight,light,normal,medium,semibold,bold,italic}`, `italic`, `not-italic`,
  `leading-{none,tight,snug,normal,relaxed}`, `tracking-{tight,normal,wide,wider,widest}`,
  `uppercase`, `label`, `underline`, `truncate`, `line-clamp-{2,3}`,
  `shadow-{sm,md,lg,card,card-hover}`, `hover:shadow-card-hover`,
  `{relative,absolute,fixed,sticky,inset-0,top-0,bottom-0,left-0,right-0,z-10,z-20,overflow-hidden,overflow-x-auto}`,
  `{object-cover,object-contain,aspect-square,aspect-video,aspect-[4/5]}`,
  `{transition,transition-colors,transition-transform,duration-300,ease-out,group,origin-left,scale-x-0,group-hover:scale-x-100,group-hover:translate-x-1}`,
  `{border,border-2,border-t,border-b,divide-y,opacity-50,opacity-70,opacity-80,cursor-pointer}`,
  `{py-12,md:py-16,px-5,md:px-20}`,
];
const input = `@import "../../app/globals.css";
@source "../previews";
${safelist.map((s) => `@source inline("${s}");`).join("\n")}
`;
const fromPath = join(PKG, "tw-input.css");
writeFileSync(fromPath, input);
const result = await postcss([tailwind({ base: ROOT })]).process(input, { from: fromPath });
rmSync(fromPath, { force: true });
// The site serves fonts from /fonts/* (public/). Point the @font-face urls at
// a package-local copy so the converter copies them into fonts/ and rewrites them.
// The converter only copies font files that live inside the package dir.
mkdirSync(join(PKG, "fonts"), { recursive: true });
for (const f of readdirSync(join(ROOT, "public/fonts"))) cpSync(join(ROOT, "public/fonts", f), join(PKG, "fonts", f));
const css = result.css.replace(/url\((['"]?)\/fonts\//g, "url($1./fonts/");
mkdirSync(PKG, { recursive: true });
writeFileSync(join(PKG, "papela.css"), css);
console.error(`  build-ds: ${Object.keys(components).length} components, ${rewrites} asset path(s) → ${ASSET_ORIGIN}, papela.css ${(css.length / 1024).toFixed(0)} KB`);
