// Bancos de palabras de Dopamina — ~200 por categoría.
// Plantilla: "Dibuja {OBJETO} {ACCIÓN} {CIERRE}."
//
// ⚠️ Reglas de curaduría (verificadas por scripts/verifica-bancos.ts):
// - OBJETOS: artículo + sustantivo; sin estados que choquen con acciones.
// - ACCIONES: gerundios independientes del lugar (nada de nadar/volar/esquiar
//   que produzcan absurdos con ciertos cierres).
// - CIERRES: lugar/momento/compañía, invariantes en género.
// - Ninguna palabra significativa se repite ENTRE bancos (dentro de un mismo
//   banco sí puede repetirse: solo una entrada por banco entra a la frase).

export const OBJETOS = [
  // ── Animales ──
  "un gato",
  "un perro salchicha",
  "un dinosaurio",
  "una rana",
  "un pulpo",
  "un caracol",
  "un oso panda",
  "un conejo",
  "una jirafa",
  "un pingüino",
  "un flamenco",
  "un erizo",
  "una tortuga",
  "un mapache",
  "un búho",
  "una llama",
  "un pez dorado",
  "un camaleón",
  "una vaca",
  "un elefante",
  "un león",
  "un tigre",
  "un zorro",
  "un lobo",
  "un koala",
  "un canguro",
  "un perezoso",
  "un armadillo",
  "un tucán",
  "un colibrí",
  "un pelícano",
  "un cangrejo",
  "un caballito de mar",
  "una medusa",
  "una ballena",
  "un delfín",
  "un tiburón",
  "una foca",
  "una morsa",
  "un castor",
  "una ardilla",
  "un murciélago",
  "un cuervo",
  "una gallina",
  "un gallo",
  "un pato",
  "un ganso",
  "un pavorreal",
  "un avestruz",
  "una iguana",
  "un sapo",
  "un grillo",
  "una catarina",
  "una abeja",
  "una hormiga",
  "un escarabajo",
  "un chapulín",
  "un ajolote",
  "un xoloitzcuintle",
  "un borrego",
  "una cabra",
  "un burro",
  "un pony",
  "un hipopótamo",
  "un rinoceronte",
  "una cebra",
  "un chango",
  "un gorila",
  "un lémur",
  "un oso polar",
  "una nutria",
  "un puercoespín",
  "un tejón",
  "un venado",
  "un alce",
  "un jabalí",
  "un oso hormiguero",
  "un tlacuache",
  "una lechuza",
  "un halcón",
  "una paloma",
  "un pollito",
  "un gusanito",
  "una oruga",
  "una libélula",
  "un caballo",
  "una alpaca",
  "un dromedario",
  "una pantera",
  "un lince",
  // ── Comida ──
  "una sandía",
  "un taco",
  "un aguacate",
  "una dona",
  "una concha de pan",
  "un helado",
  "una paleta de hielo",
  "un elote",
  "un tamal",
  "un churro",
  "un bolillo",
  "un pan de muerto",
  "un cupcake",
  "un flan",
  "una gelatina",
  "un queso",
  "una piña",
  "un plátano",
  "una fresa",
  "una manzana",
  "una pera",
  "un mango",
  "un coco",
  "una cereza",
  "un brócoli",
  "una zanahoria",
  "un chile",
  "un jitomate",
  "un nopal",
  "una calabaza",
  "una hamburguesa",
  "una pizza",
  "un sushi",
  "un pan tostado",
  "un huevo estrellado",
  "una quesadilla",
  "un bombón",
  "una uva",
  "un kiwi",
  "una tuna",
  // ── Objetos y cosas ──
  "una tetera",
  "un cactus",
  "un robot",
  "un lápiz",
  "una taza de café",
  "un paraguas",
  "una piñata",
  "un teléfono viejito",
  "una lavadora",
  "un tostador",
  "un foco",
  "un sillón",
  "una lámpara",
  "un espejo",
  "un calcetín",
  "un sombrero",
  "una bota",
  "una mochila",
  "una brújula",
  "una cámara",
  "una tele retro",
  "un tocadiscos",
  "un casete",
  "un control remoto",
  "un dado",
  "un trompo",
  "un yoyo",
  "un papalote",
  "una escoba",
  "una plancha",
  "una licuadora",
  "un sartén",
  "una cuchara",
  "un tenedor",
  "una olla",
  "una jarra",
  "una regadera",
  "un martillo",
  "un clip",
  "una goma de borrar",
  "un sacapuntas",
  "un cuaderno",
  "un buzón",
  "un semáforo",
  "una banca",
  "una maceta",
  "un ventilador",
  "un abanico",
  "una almohada",
  "una cobija",
  "un oso de peluche",
  "una marioneta",
  "un gnomo",
  "un molino de viento",
  "una campana",
  "un farol",
  "una linterna",
  "un telescopio",
  "un microscopio",
  "una lupa",
  "un imán",
  "un caleidoscopio",
  "una regla",
  "un ábaco",
  "una máquina de escribir",
  "un botón",
  "un dedal",
  "un carrete de hilo",
  "unas tijeras",
  "un crayón enorme",
  "un borrador de pizarrón",
  "un gis",
  "una engrapadora",
  "un portarretratos",
  "una veleta",
  "un candado",
  "un comal",
  "un metate",
  "un rebozo",
  "un huarache",
  // ── Personajes y fantasía ──
  "un fantasma",
  "un dragón",
  "una sirena",
  "un mago",
  "una bruja",
  "un astronauta",
  "un pirata",
  "un vampiro",
  "un yeti",
  "un duende",
  "un alebrije",
  "un unicornio",
  "un hada",
  "un esqueleto",
  "un extraterrestre",
  "un caballero medieval",
  "un ninja",
  "una momia",
  "un payaso",
  "un mimo",
  "un detective",
  "un vaquero",
  "un luchador enmascarado",
  "un genio",
  "un fénix",
  "un grifo",
  "un pegaso",
  "un centauro",
  "un minotauro",
  "un cíclope",
  "un troll",
  "un ogro",
  "un elfo",
  "una gárgola",
  "un kraken",
  "un zombi",
  "una catrina",
  "un charro",
  "un mariachi",
  "un chaneque",
  "una muñeca de trapo",
  "un soldadito de plomo",
  "un maniquí",
  "un espantapájaros",
  "un ventrílocuo",
  "un equilibrista",
  "un director de orquesta",
  "un poeta",
  "un científico",
  "un caballero andante",
  "una reina",
  "un rey",
  "un príncipe sapo",
  "un dinosaurio de peluche",
  "un robot de hojalata",
  "un títere",
  "un súper abuelito",
  "una viejita tejedora",
] as const;

export const ACCIONES = [
  // ── Música ──
  "tocando la guitarra",
  "tocando el violín",
  "tocando la batería",
  "tocando el piano",
  "tocando la flauta",
  "tocando el saxofón",
  "tocando la trompeta",
  "tocando el arpa",
  "tocando el ukelele",
  "tocando el acordeón",
  "tocando las maracas",
  "tocando la marimba",
  "tocando el contrabajo",
  "tocando la armónica",
  "cantando",
  "cantando ópera",
  "cantando las mañanitas",
  "silbando una melodía",
  "componiendo una canción",
  "grabando un disco",
  "rapeando",
  "haciendo beatbox",
  "dirigiendo un coro",
  "afinando un violonchelo",
  // ── Arte y manualidades ──
  "pintando",
  "pintando un mural",
  "pintando con acuarelas",
  "coloreando con crayones",
  "garabateando",
  "coloreando un mandala",
  "esculpiendo en barro",
  "modelando plastilina",
  "tallando madera",
  "haciendo origami",
  "bordando",
  "tejiendo",
  "cosiendo un disfraz",
  "recortando papelitos",
  "pegando calcomanías",
  "armando un collage",
  "diseñando un vestido",
  "haciendo un autorretrato",
  "haciendo esculturas de arena",
  "trazando un plano",
  "imprimiendo grabados",
  "restaurando una pintura",
  // ── Cocina ──
  "cocinando",
  "horneando",
  "amasando",
  "batiendo un pastel",
  "decorando un pastel",
  "haciendo un sándwich",
  "sirviendo sopa",
  "revolviendo chocolate caliente",
  "asando malvaviscos",
  "preparando limonada",
  "exprimiendo jugo",
  "haciendo tortillas",
  "moliendo salsa",
  "probando un guiso",
  "pelando papas",
  "haciendo palomitas",
  "espolvoreando azúcar",
  "batiendo merengue",
  "sazonando un caldo",
  "haciendo agua de jamaica",
  // ── Juegos ──
  "jugando lotería",
  "jugando ajedrez",
  "jugando damas",
  "jugando cartas",
  "jugando canicas",
  "jugando matatena",
  "jugando dominó",
  "jugando a las escondidas",
  "jugando videojuegos",
  "armando un rompecabezas",
  "apilando bloques",
  "saltando la cuerda",
  "jugando bebeleche",
  "haciendo pompas de jabón",
  "jugando serpientes y escaleras",
  "jugando al veo veo",
  "echando un volado",
  "jugando boliche",
  "lanzando aros",
  // ── Movimiento ──
  "bailando",
  "bailando salsa",
  "bailando cumbia",
  "bailando tango",
  "bailando breakdance",
  "bailando ballet",
  "patinando",
  "haciendo yoga",
  "haciendo pilates",
  "meditando",
  "haciendo lagartijas",
  "haciendo sentadillas",
  "levantando pesas",
  "dando maromas",
  "haciendo la vertical",
  "haciendo equilibrio en un pie",
  "caminando de puntitas",
  "corriendo un maratón",
  "saltando de gusto",
  "estirándose",
  "haciendo malabares",
  "andando en bici",
  "andando en monociclo",
  "brincando charcos",
  "dando piruetas",
  "haciendo caras chistosas",
  // ── Cotidianas ──
  "durmiendo",
  "roncando",
  "bostezando",
  "soñando despierto",
  "tomando té",
  "desayunando hotcakes",
  "comiendo espagueti",
  "cenando a la luz de las velas",
  "leyendo",
  "leyendo el periódico",
  "leyendo un mapa",
  "escribiendo una carta",
  "escribiendo un diario",
  "escribiendo poemas",
  "estudiando para un examen",
  "haciendo la tarea",
  "barriendo",
  "trapeando",
  "lavando los platos",
  "doblando ropa",
  "planchando una camisa",
  "regando las plantas",
  "podando un arbusto",
  "colgando un cuadro",
  "envolviendo un regalo",
  "abriendo regalos",
  "empacando una maleta",
  "cepillándose los dientes",
  "peinándose",
  "buscando sus llaves",
  "ordenando su cuarto",
  "tendiendo la cama",
  "sacudiendo el polvo",
  "tomando una siesta",
  "esperando el camión",
  "haciendo fila",
  "contando ovejas",
  "estornudando",
  "tomando un baño de espuma",
  "secándose el cabello",
  // ── Tecnología y oficios ──
  "tomando fotos",
  "tomando selfies",
  "grabando un podcast",
  "grabando un video",
  "editando una película",
  "transmitiendo en vivo",
  "haciendo una videollamada",
  "programando",
  "reparando un reloj",
  "atornillando una repisa",
  "midiendo con cinta métrica",
  "clavando un clavo",
  "pintando una barda",
  "revisando su correo",
  "sellando cartas",
  "repartiendo paquetes",
  "vendiendo globos",
  "atendiendo una tiendita",
  "cobrando en una caja registradora",
  "manejando un tractor",
  // ── Performance y social ──
  "contando chistes",
  "contando historias de miedo",
  "haciendo magia",
  "actuando en una obra",
  "dando un discurso",
  "dando una clase",
  "aplaudiendo",
  "festejando su cumpleaños",
  "soplando velitas",
  "echando porras",
  "firmando autógrafos",
  "dando abrazos",
  "resolviendo un misterio",
  "haciendo un experimento",
  "volando un dron",
  "coleccionando estampillas",
  "buscando un tesoro",
  "declamando",
  "narrando un partido",
  "haciendo trucos con cartas",
  "adivinando el futuro",
  "presentando las noticias",
  "posando para un retrato",
  "repartiendo volantes",
  "vendiendo esquites",
  "haciendo trueque",
  "organizando una tómbola",
  "rifando un premio",
  "dando la bienvenida",
] as const;

export const CIERRES = [
  // ── Naturaleza ──
  "en la luna",
  "en el bosque",
  "en la playa",
  "en la montaña",
  "en el desierto",
  "en la selva",
  "sobre una nube",
  "bajo las estrellas",
  "en un jardín",
  "junto a un lago",
  "junto a un río",
  "junto a una cascada",
  "en una isla",
  "en una cueva",
  "en un cañón",
  "en un valle",
  "en una pradera",
  "en un campo de girasoles",
  "en un huerto",
  "en un bosque de bambú",
  "bajo un árbol gigante",
  "en un invernadero",
  "en un oasis",
  "en un glaciar",
  "en un campo de lavanda",
  "en un maizal",
  "bajo la aurora boreal",
  "bajo un arcoíris",
  "entre luciérnagas",
  "en un acantilado",
  "en una duna",
  "en un manglar",
  "en un arrecife",
  "en la punta de un iceberg",
  "en un claro del bosque",
  "en la copa de una ceiba",
  "entre hojas de otoño",
  "en un campo de tulipanes",
  "junto a un géiser",
  "en una colina",
  // ── Clima y momentos ──
  "bajo la lluvia",
  "en la nieve",
  "al atardecer",
  "al amanecer",
  "a medianoche",
  "en una noche de luna llena",
  "durante una tormenta de confeti",
  "en otoño",
  "en primavera",
  "una mañana de domingo",
  "bajo el sol del mediodía",
  "entre la neblina",
  "durante un arcoíris doble",
  "en la hora dorada",
  "bajo una lluvia de estrellas",
  "mientras pasa un cometa",
  "bajo fuegos artificiales",
  "en pleno verano",
  "durante un eclipse",
  "en la primera nevada del año",
  "mientras sale el sol",
  "en una tarde lluviosa",
  "en una noche estrellada",
  "al filo del mediodía",
  // ── Ciudad y edificios ──
  "en la ciudad",
  "en un museo",
  "en un teatro",
  "en una biblioteca",
  "en un mercado",
  "en una feria",
  "en un castillo",
  "en un faro",
  "en una azotea",
  "en un callejón colorido",
  "en una plaza",
  "en un kiosco",
  "en una juguetería",
  "en una librería",
  "en una dulcería",
  "en una zapatería",
  "en un observatorio",
  "en una estación de trenes",
  "en una escuela",
  "en un estadio",
  "en un circo",
  "en un carnaval",
  "en un desfile",
  "en una boda",
  "en una kermés",
  "en un bazar",
  "en una posada",
  "en un rancho",
  "en una granja",
  "en un establo",
  "en una hacienda",
  "en un pueblito colonial",
  "en el zócalo",
  "en una vecindad",
  "en un patio",
  "en una terraza",
  "en un balcón",
  "en un ático",
  "en un vivero",
  "en una fábrica de juguetes",
  "en un estudio de televisión",
  "en un set de cine",
  "en un templo antiguo",
  "en una pirámide",
  "en un laberinto",
  "en un palacio",
  "en un fuerte abandonado",
  "en un acueducto",
  "en un puente colgante",
  "en un mirador",
  "en una fuente",
  "en un hotel elegante",
  "en un restaurante lujoso",
  "en una peluquería",
  "en un consultorio",
  "en una lavandería",
  "en un supermercado",
  "en una gasolinera",
  "en un aeropuerto",
  "en un puerto",
  "en un malecón",
  "en una alberca de pelotas",
  "en un gimnasio",
  "en una bodega misteriosa",
  "en un almacén de piñatas",
  // ── Transporte ──
  "en un tren",
  "en un barco",
  "en un globo aerostático",
  "en un tranvía",
  "en una carreta",
  "en un teleférico",
  "en un cohete",
  "sobre una alfombra voladora",
  "en un trolebús",
  "en un velero",
  "en una lancha",
  "en un vagón antiguo",
  "en un autobús de dos pisos",
  "en un ferrocarril de vapor",
  "en una canoa",
  "en un trineo",
  // ── Fantasía ──
  "en un reino de caramelo",
  "en un pueblo mágico",
  "en un bosque encantado",
  "en una casa del árbol",
  "en una torre muy alta",
  "en las nubes",
  "en el país de los dulces",
  "en el espacio",
  "en Marte",
  "en una estación espacial",
  "dentro de una pompa gigante",
  "dentro de un libro de cuentos",
  "dentro de una esfera de cristal",
  "en un mundo de papel",
  "en un sueño",
  "en el año 3000",
  "en el viejo oeste",
  "en un mundo en miniatura",
  "en gravedad cero",
  "en un planeta morado",
  "en la cola de un cometa",
  "en un iglú",
  "en una madriguera acogedora",
  "en un panal",
  "en la cima del arcoíris",
  "en un jardín colgante",
  "en una nube de algodón",
  "en el taller de un inventor",
  "en la casa de una abuelita",
  "en un rincón secreto",
  "en un columpio",
  "en una resbaladilla",
  "en un sube y baja",
  "en la sala de espera",
  "en un elevador",
  "en un anfiteatro",
  "en un salón de baile",
  "en la cubierta de un crucero",
  "en un jardín botánico",
  "en un parque de diversiones",
  "en una montaña rusa",
  "en la rueda de la fortuna",
  "en un carrusel",
  "en un campamento",
  "junto a una fogata",
  "en un muelle",
  "en un viñedo",
  "en un cafetal",
  "en un trigal",
  "en la cima de un volcán dormido",
  "junto a una laguna",
  "en un planetario",
  "en un acuario",
  "en una cabaña",
  "en una casita de jengibre",
  "dentro de una alcancía",
  "sobre una estrella fugaz",
  "en un teatro de sombras",
  "en un festival de faroles",
  "en la orilla del mundo",
] as const;
